//TYPES
export const FETCH_ALL_RESTAURANTS = 'FETCH_ALL_RESTAURANTS';
export const FIND_LOCATION_DETAILS_BY_CITY = 'FIND_LOCATION_DETAILS_BY_CITY';
export const CREATE_USER = 'CREATE_USER';
export const USER_PROFILE_DETAILS = 'PROFILE';
export const USER_PROFILE_ADDRESSES= 'ADDRESSES';
export const USER_LOGIN ='LOGIN';
export const USER_LOGOUT='LOGOUT';
export const FIND_USER_BY_USERNAME='FIND_USER_BY_USERNAME';
export const ADMIN_RESTAURANT_VIEW='ADMIN_RESTAURANT_VIEW';
export const FIND_ALL_USERS = 'FIND_ALL_USERS';

//URLS
export const USER_URL ="http://localhost:4000/api/user";
export const LOGIN_URL ="http://localhost:4000/api/login";
export const LOGOUT_URL ="http://localhost:4000/api/logout";
export const LOCAL_RESTAURANT_URL ="http://localhost:4000/api/restaurant";



export const FIND_ALL_MENUS_FOR_RESTAURANT = 'FIND_ALL_MENUS_FOR_RESTAURANT';
export const CREATE_MENU = 'CREATE_MENU';
export const DELETE_MENU = 'DELETE_MENU';
export const UPDATE_MENU = 'UPDATE_MENU';
export const SEARCH_RESTAURANTS = 'SEARCH_RESTAURANTS';
export const FIND_ALL_RESTAURANTS = 'FIND_ALL_RESTAURANTS';
export const FIND_RESTAURANT_BY_ID = 'FIND_RESTAURANT_BY_ID';
export const UPDATE_RESTAURANT_MENU = 'UPDATE_RESTAURANT_MENU';
export const FIND_MENU_BY_ID = 'FIND_MENU_BY_ID';
export const CHANGE_MENU_NAME = 'CHANGE_MENU_NAME';
export const CHANGE_MENU_CUISINE = 'CHANGE_MENU_CUISINE';
export const CHANGE_MENU_ITEMS = 'CHANGE_MENU_ITEMS';
export const ADD_TO_ORDER = 'ADD_TO_ORDER';
export const SAVE_ORDER = 'SAVE_ORDER';