export const FETCH_ALL_RESTAURANTS = 'FETCH_ALL_RESTAURANTS';
export const FIND_LOCATION_DETAILS_BY_CITY = 'FIND_LOCATION_DETAILS_BY_CITY';
export const FIND_ALL_MENUS_FOR_RESTAURANT = 'FIND_ALL_MENUS_FOR_RESTAURANT';
export const CREATE_MENU = 'CREATE_MENU';
export const DELETE_MENU = 'DELETE_MENU';
export const UPDATE_MENU = 'UPDATE_MENU';
export const SEARCH_RESTAURANTS = 'SEARCH_RESTAURANTS';